"""DNS configuration templates for gantry."""

DNSMASQ_CONFIG_TEMPLATE = """# /etc/dnsmasq.d/gantry.conf (generated)
# Auto-generated by Gantry
# Do not edit manually; changes will be overwritten

address=/.test/127.0.0.1
"""
